### ISSUE TITLE
About ERgene

### ISSUE THREAD

**Issue by zhiyongliu1** [Starlitnightly/ERgene#3]
My purpose is to find the reference genes of miRNAs in different groups. There are 6 groups (samples) in our data, 1435 miRNA. when  I set the depth "6" [ERgene.FindERG(data,6)], the error "depth larger than samples" was happened. so how I solve it? however, When it is set to 5, it is ok. In addition, how to set the Venn diagram parameters?
    Thank you!

**Comment by Starlitnightly** [comment]
Can you provide relevant error reporting information

**Comment by zhiyongliu1** [comment]
Relevant error reporting information: "depth larger than samples"
However，I couldn't be more than samples. my data like this:
gend_id   group1  group2  group3  group4 group5  group6
m1.            xx.           xx.        xx.          xx.        xx.         xx 
m2.            xx.           xx.        xx.          xx.        xx.         xx 
m3.            xx.           xx.        xx.          xx.        xx.         xx 
m4.            xx.           xx.        xx.          xx.        xx.         xx 
m5.  ................................................................................
 so ,how I set "depth"?

**Comment by Starlitnightly** [comment]
1、This is a bug to avoid overflows, which I will fix in the next release
2、If you want to plot venn in higher dimensions. You can use "ERgene.FindERG(data,3,figure=True)" to try.

**Comment by zhiyongliu1** [comment]
Thanks. Your answer is helpful.
