### ISSUE TITLE
The question of the ERgene

### ISSUE THREAD

**Issue by zhiyongliu1** [Starlitnightly/ERgene#4]
Hello, in input data, How many rows of data are allowed? In our 3840 rows data, the last data couldn't be calculated.

**Comment by Starlitnightly** [comment]
Theoretically supports unlimited rows. If the current version does not compute 3840, you can try version 1.1.0. Because I haven't tested large datasets with the updated version

**Comment by Starlitnightly** [comment]
I have just tested the GSE.txt data in the example folder, 18667 rows in total, and the program runs without any problems. At the same time, I hope every time you ask a issue, you can attach the detailed error report information

**Comment by zhiyongliu1** [comment]
ok，thank you！
| |
Zhiyong LIU
|
|
***@***.***
|
签名由网易邮箱大师定制


On 05/9/2021 ***@***.***> wrote：

Theoretically supports unlimited rows. If the current version does not compute 3840, you can try version 1.1.0. Because I haven't tested large datasets with the updated version
