### ISSUE TITLE
关于 ERgene.FindERG(data, depth) 中的depth参数

### ISSUE THREAD

**Issue by GW2017** [Starlitnightly/ERgene#5]
在 ERgene.FindERG(data, depth) 这一步，导入的数据里是有3个样品，如下图，depth应该是使用3吧，但使用ERgene.FindERG(data, 3)，报深度大于样品数的错误。**请问我的这个输入数据格式没错吧？应该怎么输入正常的命令？**
![image](https://user-images.githubusercontent.com/25303587/124710463-64a62880-df2f-11eb-8a63-f80e83923232.png)

在github上下了实例数据，使用test.csv这个文件，这个文件看着有4个样品，如下图，但是使用ERgene.FindERG(data,4)也报深度大于样本的错误
![image](https://user-images.githubusercontent.com/25303587/124710659-a8009700-df2f-11eb-998e-54a859010718.png)
如果使用ERgene.FindERG(data,3)是能运行成功的，但是使用jupyter来运行，没有生成图表。是不是因为test.csv这里面应该是有4个样品的数据，depth只用了3，虽然没报错，但是是生成不了图表的？
![image](https://user-images.githubusercontent.com/25303587/124710740-c1a1de80-df2f-11eb-96de-1d44d10d0a20.png)

**Comment by Starlitnightly** [comment]
This is a bug that was left over in order to avoid too many samples being tested for too long. I will fix it in the next version.

And if you want to generate the figure, you need to set the parameter 'figure=Ture'

Best withes!

eg.
'''def FindERG(data, depth=2, sort_num=20, verbose=False, figure=False):'''

**Comment by Starlitnightly** [comment]
If you want to use the entire sample now, you need to modify the code in the _init_.py file

**Comment by GW2017** [comment]
对于这个3个样品数据，depth不是应该设3？怎么会报错呢？应该换一个什么样的命令才能正确运行？
![image](https://user-images.githubusercontent.com/25303587/124723459-aa69ed80-df3d-11eb-873d-051d34405598.png)

**Comment by Starlitnightly** [comment]
> 对于这个3个样品数据，depth不是应该设3？怎么会报错呢？应该换一个什么样的命令才能正确运行？
> ![image](https://user-images.githubusercontent.com/25303587/124723459-aa69ed80-df3d-11eb-873d-051d34405598.png)

You can try 2.  When I wrote the program, I didn't allow the whole sample to be used, only the sample number minus one. Besides, you can modify the code of ERgene.

**Comment by GW2017** [comment]
意思是，我输入了3个细胞的样品（HBE, A549, H1299），实际上只计算了两个细胞的样品，只计算了前两个细胞的样品（HBE, A549）？H1299的rpm值并没有被纳入到内参的计算中？

**Comment by Starlitnightly** [comment]
Yes, you can try modify the code. 

from: 
if depth>(len(data.columns)-1):
        print('depth larger than samples')
        return
to:
if depth>=(len(data.columns)-1):
        print('depth larger than samples')
        return

**Comment by Starlitnightly** [comment]
I'm sorry. It should be modify to the following code. And I will update this package later.

if depth>(len(data.columns)):
print('depth larger than samples')
return

**Comment by GW2017** [comment]
另一个思路，不改目前的代码，如果想计算输入的三种细胞的数据，是不是只需要加多个凑数的第四列，第四列的数值随便填，比如说都填0，这样的话用depth=3就能计算这三种细胞的数据了？反正第四列都不纳入计算的没错吧？

**Comment by Starlitnightly** [comment]
> 另一个思路，不改目前的代码，如果想计算输入的三种细胞的数据，是不是只需要加多个凑数的第四列，第四列的数值随便填，比如说都填0，这样的话用depth=3就能计算这三种细胞的数据了？反正第四列都不纳入计算的没错吧？

You can try update the package. A new package has been released just now (Ver:1.2.8).
